[package]
name = "libsave3ds"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
sha2 = "0.9"
aes = "0.4"
cmac = "0.3"
byte_struct = "0.6"
lru = "0.5"
log = "0.4"

[dev-dependencies]
rand = "0.7"
